### ISSUE TITLE
Write cleaner code using list comprehension

### ISSUE THREAD

**Issue by kintel** [anwarhahjjeffersongeorge/Recurse-in-OpenSCAD#1]
Hi,

A small tip: Since OpenSCAD 2015.03, it's possible to use list comprehension to implement some of your functions without using recursion, which may result in cleaner code.
Examples:

```
function dummy(s, n) = [for (i=[0:n-1]) s];
function fill(v, n) = [for (i=[0:n-1]) v];
function arithmetic(s=0, i=-1, n=8) = [for (x=[0:n-1]) s+(i*x)];
function geometric(s=1, i=2, n=8) = [for (x=[0:n-1]) s*pow(i,x)];
function points_from_vecs(v0, v1) = [for (i=[0:len(v0)-1]) [v0[i], v1[i]]];
```

**Comment by anwarhahjjeffersongeorge** [comment]
Hi,
Thanks for the suggestions. Changes can be seen in the latest commit to recurse.scad.
